# Vaccom -  phần mềm hỗ trợ quản lý và tổ chức điểm tiêm chủng Vaccine
#     Copyright (C) 2021 Vaccom Development team

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.

#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

version: '3.2'

services:
  vaccom-mariadb:
    container_name: vaccom-mariadb
    image: mariadb
    hostname: vaccom-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - "./mariadb/databases:/var/lib/mysql"
    networks:
        vaccom:
          ipv4_address: 20.0.0.2

  vaccom-backend:
    container_name: vaccom-backend
    image: vaccom-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: vaccom-backend
    restart: always
    depends_on:
      - vaccom-mariadb
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - "./backend/vaccom-backend:/opt/vaccom"
    tty: true
    networks:
        vaccom:
          ipv4_address: 20.0.0.3

  vaccom-proxy:
    container_name: vaccom-proxy
    image: nginx
    hostname: vaccom-proxy
    restart: always
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - vaccom-backend
    environment:
      - CONTAINER_ROOT_PASSWORD=$CONTAINER_ROOT_PASSWORD
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - DOMAIN_LIST=$DOMAIN_LIST
      - DOMAIN=$DOMAIN
    volumes:
      - "./proxy/conf.d:/etc/nginx/conf.d"
      - "./proxy/logs:/var/log/nginx"
    ports:
      - "$PUBLIC_IP:8080:8080"
    networks:
        vaccom:
          ipv4_address: 20.0.0.4

  vaccom-frontend:
    container_name: vaccom-frontend
    image: vaccom-frontend
    hostname: vaccom-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CONTAINER_ROOT_PASSWORD=$CONTAINER_ROOT_PASSWORD
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - DOMAIN_LIST=$DOMAIN_LIST
      - DOMAIN=$DOMAIN
    volumes:
      - "./frontend/config/letsencrypt:/etc/letsencrypt"
      - "./frontend/config/nginx:/etc/nginx/conf.d"
      - "./frontend/logs/letsencrypt:/var/log/letsencrypt"
      - "./frontend/logs/nginx:/var/log/nginx"
      - "./frontend/vaccom-frontend:/usr/share/nginx/html"
    ports: 
      - '$PUBLIC_IP:443:443'
      - '$PUBLIC_IP:80:80'
    networks:
        vaccom:
          ipv4_address: 20.0.0.5

networks:
  vaccom:
    driver: bridge
    ipam:
     config:
       - subnet: 20.0.0.0/24
